### ISSUE TITLE
pretrained weights unavailable

### ISSUE THREAD

**Issue by jmamath** [hendrycks/imagenet-r#2]
Dear authors,

Can you make the resnet-50 pretrained weights available ? Extracting fails in every case.

Thank you in advance.

**Comment by hendrycks** [comment]
There should be a downloadable torchvision model.

**Comment by jmamath** [comment]
Yes, there is a downloadable .tar file, but it seems to be corrupted. For instance I have tried to open the deepaugment.pth.tar file with ZIP extractor online, but also with WinRAR on Windows and Archive Utility on Mac OS. But the file seems to be corrupted.

**Comment by hendrycks** [comment]
You can load the file directly in pytorch without untarring.
